name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v5

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
